// packages/vue/src/components/PageHeader/PageHeader.vue
<script setup lang="ts">
import { computed, h, useAttrs, useSlots, type Component, type VNodeChild } from 'vue';
import { Anchor, Box, Breadcrumbs, resolveNode, useProps, useStyles } from '@mantine-vue/core';
import { Headline, Kicker, Subheadline } from '../Typography';
import { resolveContent } from '../../utils/vue';
import type { PageHeaderBreadcrumb, PageHeaderFactory, PageHeaderOwnProps, PageHeaderSlots } from './PageHeader.types';
import { varsResolver } from './PageHeader.vars';
import classes from './PageHeader.module.css';

defineOptions({ name: 'PageHeader', inheritAttrs: false });

// Tudo `undefined` aqui para que os defaults de `theme.components.PageHeader` funcionem via useProps
const rawProps = withDefaults(defineProps<PageHeaderOwnProps>(), {
  kicker: undefined,
  title: undefined,
  description: undefined,
  icon: undefined,
  iconSize: undefined,
  actions: undefined,
  breadcrumbs: undefined,
  linkComponent: undefined,
  size: undefined,
  classNames: undefined,
  styles: undefined,
  vars: undefined,
  unstyled: undefined,
});
defineSlots<PageHeaderSlots>();

const slots = useSlots();
const attrs = useAttrs();

const props = useProps('PageHeader', { linkComponent: 'a', size: 'headline' }, rawProps);

// Getters: classNames/styles/class/style continuam reativos depois do setup
const getStyles = useStyles<PageHeaderFactory>({
  name: 'PageHeader',
  classes,
  props,
  get className() {
    return attrs.class;
  },
  get style() {
    return attrs.style as any;
  },
  get classNames() {
    return props.classNames as any;
  },
  get styles() {
    return props.styles as any;
  },
  get vars() {
    return props.vars as any;
  },
  get unstyled() {
    return props.unstyled;
  },
  varsResolver,
});

/** Renderiza um `MantineNode` (VNode, texto ou função) como componente estável. */
const RenderNode = (p: { node: VNodeChild }) => p.node;
RenderNode.props = ['node'];

const linkComponent = computed<string | Component>(() => props.linkComponent ?? 'a');
const kicker = computed(() => resolveContent(props.kicker, slots.kicker));
const title = computed(() => resolveNode(props.title, slots.title));
const description = computed(() => resolveContent(props.description, slots.description));
const icon = computed(() => resolveContent(props.icon, slots.icon));
const actions = computed(() => resolveContent(props.actions, slots.actions));
const rootAttrs = computed(() => {
  const { class: _class, style: _style, ...rest } = attrs;
  return rest;
});

const crumbNode = (crumb: PageHeaderBreadcrumb, index: number) =>
  crumb.href
    ? h(
        Anchor as any,
        {
          key: index,
          component: linkComponent.value,
          href: crumb.href,
          ...(linkComponent.value !== 'a' && { to: crumb.href }),
          fz: 'sm',
        },
        () => resolveNode(crumb.label),
      )
    : h(Box as any, { key: index, component: 'span', c: 'var(--ds-text-3)', fz: 'sm' }, () => resolveNode(crumb.label));
</script>

<template>
  <Box v-bind="{ ...rootAttrs, ...getStyles('root') }">
    <Breadcrumbs
      v-if="props.breadcrumbs && props.breadcrumbs.length > 0"
      v-bind="getStyles('breadcrumbs')"
      fz="sm"
      :separator-margin="6"
    >
      <RenderNode :node="props.breadcrumbs.map(crumbNode)" />
    </Breadcrumbs>
    <div v-bind="getStyles('header')">
      <div v-bind="getStyles('main')">
        <div v-if="icon !== undefined" v-bind="getStyles('icon')" aria-hidden="true">
          <RenderNode :node="icon" />
        </div>
        <div v-bind="getStyles('body')">
          <Kicker v-if="kicker !== undefined" v-bind="getStyles('kicker')">
            <RenderNode :node="kicker" />
          </Kicker>
          <Headline
            v-if="props.size === 'display'"
            component="h1"
            size="lg"
            fz="var(--type-display-sm)"
            :lh="1.15"
            :mt="8"
            v-bind="getStyles('title')"
          >
            <RenderNode :node="title" />
          </Headline>
          <Headline v-else component="h1" size="lg" :mt="kicker !== undefined ? 8 : 0" v-bind="getStyles('title')">
            <RenderNode :node="title" />
          </Headline>
          <Subheadline
            v-if="description !== undefined"
            component="div"
            size="lg"
            c="var(--ds-text-2)"
            :maw="640"
            :mt="8"
            v-bind="getStyles('description')"
          >
            <RenderNode :node="description" />
          </Subheadline>
        </div>
      </div>
      <div v-if="actions !== undefined" v-bind="getStyles('actions')">
        <RenderNode :node="actions" />
      </div>
    </div>
  </Box>
</template>

// packages/ui/src/components/PageHeader/PageHeader.tsx
import {
  Anchor,
  Box,
  Breadcrumbs,
  factory,
  rem,
  useProps,
  useStyles,
  type BoxProps,
  type ElementProps,
  type Factory,
  type StylesApiProps,
} from '@mantine/core';
import { Kicker, Headline, Subheadline } from '../Typography';
import classes from './PageHeader.module.css';

export interface PageHeaderBreadcrumb {
  label: React.ReactNode;
  href?: string;
}

export type PageHeaderStylesNames =
  | 'root'
  | 'breadcrumbs'
  | 'header'
  | 'main'
  | 'icon'
  | 'body'
  | 'kicker'
  | 'title'
  | 'description'
  | 'actions';

export type PageHeaderCssVariables = {
  root: '--page-header-icon-size';
};

export interface PageHeaderProps
  extends BoxProps,
    StylesApiProps<PageHeaderFactory>,
    Omit<ElementProps<'div'>, 'title'> {
  kicker?: React.ReactNode;
  title: React.ReactNode;
  description?: React.ReactNode;
  /** Ícone à esquerda do título (ex.: `<IconUsers />`), num quadro suave na cor primária */
  icon?: React.ReactNode;
  /** Tamanho do quadro do ícone (px ou CSS) @default 48 */
  iconSize?: number | string;
  /** Botões à direita do título */
  actions?: React.ReactNode;
  breadcrumbs?: PageHeaderBreadcrumb[];
  /** Componente dos links do breadcrumb (ex.: Link do react-router) @default 'a' */
  linkComponent?: React.ElementType;
  /** `display` usa display-small (página principal); `headline` usa headline-large @default 'headline' */
  size?: 'display' | 'headline';
}

export type PageHeaderFactory = Factory<{
  props: PageHeaderProps;
  ref: HTMLDivElement;
  stylesNames: PageHeaderStylesNames;
  vars: PageHeaderCssVariables;
}>;

const defaultProps: Partial<PageHeaderProps> = {
  linkComponent: 'a',
  size: 'headline',
};

/** Cabeçalho de página: breadcrumbs, ícone, kicker, título, descrição e ações. */
export const PageHeader = factory<PageHeaderFactory>((_props) => {
  const props = useProps('PageHeader', defaultProps, _props);
  const {
    classNames, className, style, styles, unstyled, vars, attributes,
    kicker, title, description, icon, iconSize, actions, breadcrumbs, linkComponent = 'a', size, ...others
  } = props;

  const getStyles = useStyles<PageHeaderFactory>({
    name: 'PageHeader',
    classes,
    props,
    className,
    style,
    classNames,
    styles,
    unstyled,
    attributes,
    vars,
    varsResolver: (_theme, { iconSize: s }) => ({
      root: { '--page-header-icon-size': s === undefined ? undefined : typeof s === 'number' ? rem(s) : s },
    }),
  });

  return (
    <Box {...getStyles('root')} {...others}>
      {breadcrumbs && breadcrumbs.length > 0 && (
        <Breadcrumbs {...getStyles('breadcrumbs')} fz="sm" separatorMargin={6}>
          {breadcrumbs.map((crumb, index) =>
            crumb.href ? (
              <Anchor key={index} component={linkComponent as 'a'} href={crumb.href} {...(linkComponent !== 'a' && { to: crumb.href })} fz="sm">
                {crumb.label}
              </Anchor>
            ) : (
              <Box key={index} component="span" c="var(--ds-text-3)" fz="sm">
                {crumb.label}
              </Box>
            ),
          )}
        </Breadcrumbs>
      )}
      <div {...getStyles('header')}>
        <div {...getStyles('main')}>
          {icon && (
            <div {...getStyles('icon')} aria-hidden>
              {icon}
            </div>
          )}
          <div {...getStyles('body')}>
            {kicker && <Kicker {...getStyles('kicker')}>{kicker}</Kicker>}
            {size === 'display' ? (
              <Headline component="h1" size="lg" fz="var(--type-display-sm)" lh={1.15} mt={8} {...getStyles('title')}>
                {title}
              </Headline>
            ) : (
              <Headline component="h1" size="lg" mt={kicker ? 8 : 0} {...getStyles('title')}>
                {title}
              </Headline>
            )}
            {description && (
              <Subheadline component="div" size="lg" c="var(--ds-text-2)" maw={640} mt={8} {...getStyles('description')}>
                {description}
              </Subheadline>
            )}
          </div>
        </div>
        {actions && <div {...getStyles('actions')}>{actions}</div>}
      </div>
    </Box>
  );
});

PageHeader.classes = classes;
PageHeader.displayName = '@jcdecor/ui/PageHeader';
