// apps/docs/src/demos/pin-input/coupon.demo.vue
<script lang="ts">
export const meta = { centered: true };
</script>

<script setup lang="ts">
import { computed, ref } from 'vue';
import { PinInput, Stack, Text } from '@jcdecor/vue';

const cupom = ref('');
const valido = computed(() => cupom.value === 'DECO10');
</script>

<template>
  <Stack align="center" gap="xs">
    <Text id="cupom-label" fz="sm" :fw="500" c="var(--ds-text-2)">Cupom de desconto</Text>
    <!-- O PinInput do Mantine Vue ainda não tem a prop `success`: a borda verde vem de `styles`. -->
    <PinInput
      :model-value="cupom"
      :length="6"
      type="alphanumeric"
      aria-label="Cupom de desconto"
      :error="cupom.length === 6 && !valido"
      :styles="valido ? { input: { borderColor: 'var(--ds-success)' } } : undefined"
      @update:model-value="(value) => (cupom = value.toUpperCase())"
    />
    <Text fz="sm" :c="valido ? 'var(--ds-success)' : cupom.length === 6 ? 'var(--ds-error)' : 'var(--ds-text-3)'">
      {{ valido ? 'Cupom aplicado: 10% de desconto' : cupom.length === 6 ? 'Cupom inválido ou expirado' : 'Experimente DECO10' }}
    </Text>
  </Stack>
</template>

// apps/docs/src/demos/pin-input/coupon.demo.tsx
import { useState } from 'react';
import { PinInput, Stack, Text } from '@jcdecor/ui';
import type { DemoMeta } from '../../kit/demos';

export const meta: DemoMeta = { centered: true };

export default function Demo() {
  const [cupom, setCupom] = useState('');
  const valido = cupom === 'DECO10';

  return (
    <Stack align="center" gap="xs">
      <Text fz="sm" fw={500} c="var(--ds-text-2)" id="cupom-label">
        Cupom de desconto
      </Text>
      <PinInput
        length={6}
        type="alphanumeric"
        value={cupom}
        onChange={(value) => setCupom(value.toUpperCase())}
        ariaLabel="Cupom de desconto"
        error={cupom.length === 6 && !valido}
        success={valido}
      />
      <Text fz="sm" c={valido ? 'var(--ds-success)' : cupom.length === 6 ? 'var(--ds-error)' : 'var(--ds-text-3)'}>
        {valido ? 'Cupom aplicado: 10% de desconto' : cupom.length === 6 ? 'Cupom inválido ou expirado' : 'Experimente DECO10'}
      </Text>
    </Stack>
  );
}
