// apps/docs/src/demos/scroll-area/infinite.demo.vue
<script lang="ts">
export const meta = { centered: true, maxWidth: 420 };
</script>

<script setup lang="ts">
import { ref } from 'vue';
import { Loader, Paper, ScrollArea, Text } from '@jcdecor/vue';

const items = ref(10);
const loading = ref(false);

function loadMore() {
  if (loading.value || items.value >= 40) return;
  loading.value = true;
  setTimeout(() => {
    items.value += 10;
    loading.value = false;
  }, 600);
}
</script>

<template>
  <Paper with-border w="100%">
    <ScrollArea :h="240" px="md" @bottom-reached="loadMore">
      <Text v-for="i in items" :key="i" fz="sm" py="xs" :style="{ borderBottom: '1px solid var(--ds-border-soft)' }">
        Avaliação #{{ i }} — produto chegou bem embalado
      </Text>
      <Loader v-if="loading" size="sm" my="sm" mx="auto" display="block" />
    </ScrollArea>
  </Paper>
</template>

// apps/docs/src/demos/scroll-area/infinite.demo.tsx
import { Loader, Paper, ScrollArea, Text } from '@jcdecor/ui';
import { useState } from 'react';
import type { DemoMeta } from '../../kit/demos';

export const meta: DemoMeta = { centered: true, maxWidth: 420 };

export default function Demo() {
  const [items, setItems] = useState(10);
  const [loading, setLoading] = useState(false);

  const loadMore = () => {
    if (loading || items >= 40) return;
    setLoading(true);
    setTimeout(() => {
      setItems((n) => n + 10);
      setLoading(false);
    }, 600);
  };

  return (
    <Paper withBorder w="100%">
      <ScrollArea h={240} px="md" onBottomReached={loadMore}>
        {Array.from({ length: items }, (_, i) => (
          <Text key={i} fz="sm" py="xs" style={{ borderBottom: '1px solid var(--ds-border-soft)' }}>
            Avaliação #{i + 1} — produto chegou bem embalado
          </Text>
        ))}
        {loading && <Loader size="sm" my="sm" mx="auto" display="block" />}
      </ScrollArea>
    </Paper>
  );
}
