// apps/docs/src/demos/mask-input/raw-value.demo.vue
<script lang="ts">
export const meta = { centered: true, maxWidth: 420 };
</script>

<script setup lang="ts">
import { ref } from 'vue';
import { Code, MaskInput, Stack, Text } from '@jcdecor/vue';

const raw = ref('');
const cidade = ref<string | null>(null);

function onChangeRaw(value: string) {
  raw.value = value;
  cidade.value = null;
}
</script>

<template>
  <Stack w="100%" gap="xs">
    <MaskInput
      label="CEP de entrega"
      mask="99999-999"
      always-show-mask
      input-mode="numeric"
      @change-raw="onChangeRaw"
      @complete="cidade = 'São Paulo · SP — frete grátis'"
    />
    <Text fz="sm" c="var(--ds-text-2)">
      Valor enviado à API: <Code>{{ raw || '—' }}</Code>
    </Text>
    <Text v-if="cidade" fz="sm" c="var(--ds-success)">{{ cidade }}</Text>
  </Stack>
</template>

// apps/docs/src/demos/mask-input/raw-value.demo.tsx
import { useState } from 'react';
import { Code, MaskInput, Stack, Text } from '@jcdecor/ui';
import type { DemoMeta } from '../../kit/demos';

export const meta: DemoMeta = { centered: true, maxWidth: 420 };

export default function Demo() {
  const [raw, setRaw] = useState('');
  const [cidade, setCidade] = useState<string | null>(null);

  return (
    <Stack w="100%" gap="xs">
      <MaskInput
        label="CEP de entrega"
        mask="99999-999"
        alwaysShowMask
        onChangeRaw={(value) => {
          setRaw(value);
          setCidade(null);
        }}
        onComplete={() => setCidade('São Paulo · SP — frete grátis')}
        inputMode="numeric"
      />
      <Text fz="sm" c="var(--ds-text-2)">
        Valor enviado à API: <Code>{raw || '—'}</Code>
      </Text>
      {cidade && (
        <Text fz="sm" c="var(--ds-success)">
          {cidade}
        </Text>
      )}
    </Stack>
  );
}
