// packages/ui/src/components/TopNav/TopNav.tsx
import {
  Box,
  Burger,
  Collapse,
  factory,
  useProps,
  useStyles,
  type BoxProps,
  type ElementProps,
  type Factory,
  type StylesApiProps,
} from '@mantine/core';
import { useEffect, useRef } from 'react';
import { useDisclosure, useId } from '@mantine/hooks';
import { JcLogo } from '../../brand/Brand';
import classes from './TopNav.module.css';

export type TopNavStylesNames = 'root' | 'brand' | 'links' | 'link' | 'linkSection' | 'linkLabel' | 'right' | 'burger' | 'mobileLinks';

export interface TopNavLink {
  label: React.ReactNode;
  href?: string;
  active?: boolean;
  /** Ícone/conteúdo antes do texto (como `leftSection` do Mantine) */
  leftSection?: React.ReactNode;
  /** Conteúdo depois do texto (ex.: contador, chevron) */
  rightSection?: React.ReactNode;
  /** Desabilita o link (sem navegação nem `onClick`) */
  disabled?: boolean;
  /** Nome acessível, necessário quando o link mostra só um ícone */
  'aria-label'?: string;
  onClick?: (event: React.MouseEvent) => void;
}

export interface TopNavProps extends BoxProps, StylesApiProps<TopNavFactory>, ElementProps<'div'> {
  /** Marca à esquerda @default <JcLogo variant="dark" /> (a barra é navy em ambos os temas) */
  brand?: React.ReactNode;
  /** Link da marca; `null` renderiza a marca como texto @default '/' */
  brandHref?: string | null;
  links?: TopNavLink[];
  /** Componente usado nos links (ex.: `Link` do react-router, recebe `to`/`href`) @default 'a' */
  linkComponent?: React.ElementType;
  /** Conteúdo à direita (ex.: ThemeToggle, avatar) */
  rightSection?: React.ReactNode;
  /** Esconde os links em telas pequenas e mostra um hambúrguer @default true */
  collapseOnMobile?: boolean;
}

export type TopNavFactory = Factory<{
  props: TopNavProps;
  ref: HTMLDivElement;
  stylesNames: TopNavStylesNames;
}>;

/** Barra de navegação Obsidian dos painéis (ds-nav). */
export const TopNav = factory<TopNavFactory>((_props) => {
  const props = useProps('TopNav', { brand: <JcLogo variant="dark" size={28} />, brandHref: '/', links: [], linkComponent: 'a', collapseOnMobile: true }, _props);
  const {
    classNames, className, style, styles, unstyled, vars, attributes,
    brand, brandHref, links, linkComponent: LinkComponent = 'a', rightSection, collapseOnMobile, ...others
  } = props;
  const [opened, { toggle, close }] = useDisclosure(false);
  const mobileId = useId();
  const headerRef = useRef<HTMLElement>(null);
  const burgerRef = useRef<HTMLButtonElement>(null);

  // Esc fecha o menu mobile; o foco volta ao hambúrguer se estava dentro da barra/menu
  useEffect(() => {
    if (!opened) return;
    const onKeyDown = (event: KeyboardEvent) => {
      if (event.key !== 'Escape') return;
      const focusInside = headerRef.current?.contains(document.activeElement);
      close();
      if (focusInside) burgerRef.current?.focus();
    };
    document.addEventListener('keydown', onKeyDown);
    return () => document.removeEventListener('keydown', onKeyDown);
  }, [opened, close]);

  const getStyles = useStyles<TopNavFactory>({
    name: 'TopNav',
    classes,
    props,
    className,
    style,
    classNames,
    styles,
    unstyled,
    attributes,
    vars,
  });

  const renderLinks = (onNavigate?: () => void) =>
    links!.map((link, index) => {
      const isButton = !link.href || link.disabled;
      const Component: React.ElementType = isButton ? 'button' : LinkComponent;
      const linkProps = isButton
        ? { type: 'button', disabled: link.disabled || undefined }
        : LinkComponent === 'a'
          ? { href: link.href }
          : { to: link.href, href: link.href };
      return (
        <Component
          key={index}
          {...linkProps}
          {...getStyles('link')}
          data-active={link.active || undefined}
          data-disabled={link.disabled || undefined}
          aria-current={link.active ? 'page' : undefined}
          aria-label={link['aria-label']}
          onClick={(event: React.MouseEvent) => {
            if (link.disabled) return;
            link.onClick?.(event);
            onNavigate?.();
          }}
        >
          {link.leftSection || link.rightSection ? (
            <>
              {link.leftSection && <span {...getStyles('linkSection')} data-position="left">{link.leftSection}</span>}
              {link.label !== undefined && link.label !== null && link.label !== '' && <span {...getStyles('linkLabel')}>{link.label}</span>}
              {link.rightSection && <span {...getStyles('linkSection')} data-position="right">{link.rightSection}</span>}
            </>
          ) : (
            link.label
          )}
        </Component>
      );
    });

  const BrandComponent: React.ElementType = brandHref === null ? 'span' : LinkComponent;
  const brandProps = brandHref === null ? {} : LinkComponent === 'a' ? { href: brandHref } : { to: brandHref, href: brandHref };

  return (
    <header ref={headerRef}>
      <Box {...getStyles('root')} mod={{ collapse: collapseOnMobile }} {...others}>
        <BrandComponent {...brandProps} {...getStyles('brand')}>
          {brand}
        </BrandComponent>
        <nav {...getStyles('links')} aria-label="Principal">
          {renderLinks()}
        </nav>
        <div {...getStyles('right')}>
          {rightSection}
          {collapseOnMobile && links!.length > 0 && (
            <Burger
              ref={burgerRef}
              opened={opened}
              onClick={toggle}
              size="sm"
              aria-label="Abrir menu"
              aria-expanded={opened}
              aria-controls={mobileId}
              {...getStyles('burger')}
            />
          )}
        </div>
      </Box>
      {collapseOnMobile && links!.length > 0 && (
        <Collapse expanded={opened}>
          <nav {...getStyles('mobileLinks')} id={mobileId} aria-label="Principal (mobile)">
            {renderLinks(close)}
          </nav>
        </Collapse>
      )}
    </header>
  );
});

TopNav.classes = classes;
TopNav.displayName = '@jcdecor/ui/TopNav';

// packages/vue/src/components/TopNav/TopNav.vue
<script setup lang="ts">
import { computed, h, ref, useAttrs, useSlots, type Component, type VNodeChild } from 'vue';
import { Box, Burger, Collapse, resolveNode, useProps, useStyles, type MantineNode } from '@mantine-vue/core';
import { useDisclosure, useId, useWindowEvent } from '@mantine-vue/hooks';
import { JcLogo } from '../../brand/Brand';
import type { TopNavFactory, TopNavLink, TopNavOwnProps, TopNavSlots } from './TopNav.types';
import classes from './TopNav.module.css';

defineOptions({ name: 'TopNav', inheritAttrs: false });

// Tudo `undefined` aqui para que os defaults de `theme.components.TopNav` funcionem via useProps
const rawProps = withDefaults(defineProps<TopNavOwnProps>(), {
  brand: undefined,
  brandHref: undefined,
  links: undefined,
  linkComponent: undefined,
  rightSection: undefined,
  collapseOnMobile: undefined,
  classNames: undefined,
  styles: undefined,
  vars: undefined,
  unstyled: undefined,
});
defineSlots<TopNavSlots>();

const slots = useSlots();
const attrs = useAttrs();

const props = useProps(
  'TopNav',
  {
    brand: () => h(JcLogo, { variant: 'dark', size: 28 }),
    brandHref: '/',
    links: [],
    linkComponent: 'a',
    collapseOnMobile: true,
  },
  rawProps,
);

const [opened, { toggle, close }] = useDisclosure(false);
const mobileId = useId();
const headerEl = ref<HTMLElement | null>(null);

// Esc fecha o menu mobile; o foco volta ao hambúrguer se estava dentro da barra/menu
useWindowEvent('keydown', (event: KeyboardEvent) => {
  if (event.key !== 'Escape' || !opened.value) return;
  const header = headerEl.value;
  const focusInside = !!header?.contains(document.activeElement);
  close();
  if (focusInside) header?.querySelector<HTMLElement>(`[aria-controls="${mobileId.value}"]`)?.focus();
});

// Getters: classNames/styles/class/style continuam reativos depois do setup
const getStyles = useStyles<TopNavFactory>({
  name: 'TopNav',
  classes,
  props,
  get className() {
    return attrs.class;
  },
  get style() {
    return attrs.style as any;
  },
  get classNames() {
    return props.classNames as any;
  },
  get styles() {
    return props.styles as any;
  },
  get vars() {
    return props.vars as any;
  },
  get unstyled() {
    return props.unstyled;
  },
});

/** Renderiza um `MantineNode` (VNode, texto ou função) como componente estável. */
const RenderNode = (p: { node: VNodeChild }) => p.node;
RenderNode.props = ['node'];

const linkComponent = computed<string | Component>(() => props.linkComponent ?? 'a');
const hrefProps = (href: string) => (linkComponent.value === 'a' ? { href } : { to: href, href });

const withChildren = (component: string | Component, children: VNodeChild) =>
  typeof component === 'string' ? children : { default: () => children };

const renderLinks = (onNavigate?: () => void) =>
  (props.links ?? []).map((link: TopNavLink, index: number) => {
    const isButton = !link.href || link.disabled;
    const component = isButton ? 'button' : linkComponent.value;
    const linkProps = isButton ? { type: 'button', disabled: link.disabled || undefined } : hrefProps(link.href!);
    const hasLabel = link.label !== undefined && link.label !== null && link.label !== '';
    const hasSections = link.leftSection != null || link.rightSection != null;
    const children = !hasSections ? resolveNode(link.label as MantineNode) : [
      link.leftSection != null
        ? h('span', { ...getStyles('linkSection'), 'data-position': 'left' }, [resolveNode(link.leftSection)])
        : null,
      hasLabel ? h('span', getStyles('linkLabel'), [resolveNode(link.label as MantineNode)]) : null,
      link.rightSection != null
        ? h('span', { ...getStyles('linkSection'), 'data-position': 'right' }, [resolveNode(link.rightSection)])
        : null,
    ];
    return h(
      component as any,
      {
        key: index,
        ...linkProps,
        ...getStyles('link'),
        'data-active': link.active || undefined,
        'data-disabled': link.disabled || undefined,
        'aria-current': link.active ? 'page' : undefined,
        'aria-label': link['aria-label'],
        onClick: (event: MouseEvent) => {
          if (link.disabled) return;
          link.onClick?.(event);
          onNavigate?.();
        },
      },
      withChildren(component, children) as any,
    );
  });

const brandNode = computed(() => resolveNode(props.brand, slots.brand));
const rightNode = computed(() => resolveNode(props.rightSection, slots.rightSection));
const brandComponent = computed(() => (props.brandHref === null ? 'span' : linkComponent.value));
const brandProps = computed(() => (props.brandHref === null ? {} : hrefProps(props.brandHref ?? '/')));
const withBurger = computed(() => !!props.collapseOnMobile && (props.links ?? []).length > 0);
const rootMod = computed(() => [{ collapse: props.collapseOnMobile }, (attrs as any).mod]);
</script>

<template>
  <header ref="headerEl">
    <Box v-bind="{ ...attrs, ...getStyles('root') }" :mod="rootMod">
      <component :is="brandComponent" v-bind="{ ...brandProps, ...getStyles('brand') }">
        <RenderNode :node="brandNode" />
      </component>
      <nav v-bind="getStyles('links')" aria-label="Principal">
        <RenderNode :node="renderLinks()" />
      </nav>
      <div v-bind="getStyles('right')">
        <RenderNode :node="rightNode" />
        <Burger
          v-if="withBurger"
          :opened="opened"
          size="sm"
          aria-label="Abrir menu"
          :aria-expanded="opened"
          :aria-controls="mobileId"
          v-bind="getStyles('burger')"
          @click="toggle"
        />
      </div>
    </Box>
    <Collapse v-if="withBurger" :expanded="opened">
      <nav v-bind="getStyles('mobileLinks')" :id="mobileId" aria-label="Principal (mobile)">
        <RenderNode :node="renderLinks(close)" />
      </nav>
    </Collapse>
  </header>
</template>
