// apps/docs/src/demos/file-button/multiple.demo.vue
<script lang="ts">
export const meta = { centered: true, maxWidth: 420 };
</script>

<script setup lang="ts">
import { ref } from 'vue';
import { Button, FileButton, Group, List, ListItem, Stack, Text } from '@jcdecor/vue';
import { IconTrash, IconUpload } from '@tabler/icons-vue';

const fotos = ref<File[]>([]);
/** Recebe do FileButton a função que limpa o `<input type="file">`. */
let resetInput = () => {};

const limpar = () => {
  fotos.value = [];
  resetInput();
};
</script>

<template>
  <Stack>
    <Group>
      <FileButton v-model="fotos" :reset-ref="(reset: () => void) => (resetInput = reset)" accept="image/*" multiple v-slot="props">
        <Button variant="outline" v-bind="props">
          <template #leftSection><IconUpload :size="18" /></template>
          Escolher fotos
        </Button>
      </FileButton>
      <Button variant="subtle" color="danger" :disabled="fotos.length === 0" @click="limpar">
        <template #leftSection><IconTrash :size="18" /></template>
        Limpar
      </Button>
    </Group>
    <List v-if="fotos.length > 0" size="sm">
      <ListItem v-for="file in fotos" :key="file.name">{{ file.name }}</ListItem>
    </List>
    <Text v-else fz="sm" c="var(--ds-text-3)">Envie até 5 fotos do cômodo para receber uma sugestão de produto.</Text>
  </Stack>
</template>

// apps/docs/src/demos/file-button/multiple.demo.tsx
import { useRef, useState } from 'react';
import { Button, FileButton, Group, List, Stack, Text } from '@jcdecor/ui';
import { IconTrash, IconUpload } from '@tabler/icons-react';
import type { DemoMeta } from '../../kit/demos';

export const meta: DemoMeta = { centered: true, maxWidth: 420 };

export default function Demo() {
  const [fotos, setFotos] = useState<File[]>([]);
  const resetRef = useRef<() => void>(null);

  const limpar = () => {
    setFotos([]);
    resetRef.current?.();
  };

  return (
    <Stack>
      <Group>
        <FileButton resetRef={resetRef} onChange={setFotos} accept="image/*" multiple>
          {(props) => (
            <Button variant="outline" leftSection={<IconUpload size={18} />} {...props}>
              Escolher fotos
            </Button>
          )}
        </FileButton>
        <Button variant="subtle" color="danger" leftSection={<IconTrash size={18} />} disabled={fotos.length === 0} onClick={limpar}>
          Limpar
        </Button>
      </Group>
      {fotos.length > 0 ? (
        <List size="sm">
          {fotos.map((file) => (
            <List.Item key={file.name}>{file.name}</List.Item>
          ))}
        </List>
      ) : (
        <Text fz="sm" c="var(--ds-text-3)">
          Envie até 5 fotos do cômodo para receber uma sugestão de produto.
        </Text>
      )}
    </Stack>
  );
}
