// apps/docs/src/demos/json-input/config.demo.vue
<script lang="ts">
export const meta = { centered: true, maxWidth: 560 };
</script>

<script setup lang="ts">
import { computed, ref } from 'vue';
import { Code, JsonInput, Stack, Text } from '@jcdecor/vue';

const inicial = JSON.stringify(
  { vitrine: { colunas: 4, mostrarPreco: true }, destaque: ['pisos', 'cortinas'], frete: { gratisAcima: 499 } },
  null,
  2,
);

const value = ref(inicial);
const colunas = computed<number | undefined>(() => {
  try {
    return JSON.parse(value.value).vitrine?.colunas;
  } catch {
    return undefined;
  }
});
</script>

<template>
  <Stack w="100%">
    <JsonInput
      v-model="value"
      label="JSON de configuração do painel"
      validation-error="JSON inválido"
      format-on-blur
      autosize
      :min-rows="6"
      :indent-spaces="2"
    />
    <Text fz="sm" c="var(--ds-text-2)">
      Colunas da vitrine: <Code>{{ colunas ?? '—' }}</Code>
    </Text>
  </Stack>
</template>

// apps/docs/src/demos/json-input/config.demo.tsx
import { useState } from 'react';
import { Code, JsonInput, Stack, Text } from '@jcdecor/ui';
import type { DemoMeta } from '../../kit/demos';

export const meta: DemoMeta = { centered: true, maxWidth: 560 };

const inicial = JSON.stringify(
  { vitrine: { colunas: 4, mostrarPreco: true }, destaque: ['pisos', 'cortinas'], frete: { gratisAcima: 499 } },
  null,
  2,
);

export default function Demo() {
  const [value, setValue] = useState(inicial);
  let colunas: number | undefined;
  try {
    colunas = JSON.parse(value).vitrine?.colunas;
  } catch {
    colunas = undefined;
  }

  return (
    <Stack w="100%">
      <JsonInput
        label="JSON de configuração do painel"
        value={value}
        onChange={setValue}
        validationError="JSON inválido"
        formatOnBlur
        autosize
        minRows={6}
        indentSpaces={2}
      />
      <Text fz="sm" c="var(--ds-text-2)">
        Colunas da vitrine: <Code>{colunas ?? '—'}</Code>
      </Text>
    </Stack>
  );
}
