// apps/docs/src/demos/loading-overlay/saving-form.demo.tsx
import { useState } from 'react';
import { Box, Button, Group, LoadingOverlay, NumberInput, Stack, TextInput, Textarea } from '@jcdecor/ui';
import type { DemoMeta } from '../../kit/demos';

export const meta: DemoMeta = { maxWidth: 480, centered: true };

export default function Demo() {
  const [saving, setSaving] = useState(false);

  const save = () => {
    setSaving(true);
    window.setTimeout(() => setSaving(false), 2000);
  };

  return (
    <Box pos="relative">
      <LoadingOverlay visible={saving} zIndex={10} overlayProps={{ radius: 'md' }} />
      <Stack>
        <TextInput label="Nome do produto" defaultValue="Cortina blackout Grafite" />
        <Group grow>
          <NumberInput label="Preço" defaultValue={329} prefix="R$ " decimalSeparator="," thousandSeparator="." decimalScale={2} fixedDecimalScale />
          <NumberInput label="Estoque" defaultValue={48} min={0} />
        </Group>
        <Textarea label="Descrição" defaultValue="Bloqueia 100% da luz. Tecido com toque de linho, ilhós cromados." autosize minRows={2} />
        <Group justify="flex-end">
          <Button variant="subtle" disabled={saving}>
            Descartar
          </Button>
          <Button onClick={save} loading={saving}>
            Salvar alterações
          </Button>
        </Group>
      </Stack>
    </Box>
  );
}

// apps/docs/src/demos/loading-overlay/saving-form.demo.vue
<script lang="ts">
export const meta = { maxWidth: 480, centered: true };
</script>

<script setup lang="ts">
import { ref } from 'vue';
import { Box, Button, Group, LoadingOverlay, NumberInput, Stack, TextInput, Textarea } from '@jcdecor/vue';

const saving = ref(false);

const save = () => {
  saving.value = true;
  window.setTimeout(() => (saving.value = false), 2000);
};
</script>

<template>
  <Box pos="relative">
    <LoadingOverlay :visible="saving" :z-index="10" :overlay-props="{ radius: 'md' }" />
    <Stack>
      <TextInput label="Nome do produto" default-value="Cortina blackout Grafite" />
      <Group grow>
        <NumberInput
          label="Preço"
          :default-value="329"
          prefix="R$ "
          decimal-separator=","
          thousand-separator="."
          :decimal-scale="2"
          fixed-decimal-scale
        />
        <NumberInput label="Estoque" :default-value="48" :min="0" />
      </Group>
      <Textarea label="Descrição" default-value="Bloqueia 100% da luz. Tecido com toque de linho, ilhós cromados." autosize :min-rows="2" />
      <Group justify="flex-end">
        <Button variant="subtle" :disabled="saving">Descartar</Button>
        <Button :loading="saving" @click="save">Salvar alterações</Button>
      </Group>
    </Stack>
  </Box>
</template>
