// packages/vue/src/components/ContentCard/ContentCard.vue
<script setup lang="ts">
import { useAttrs, useSlots } from 'vue';
import { useProps, useStyles } from '@mantine-vue/core';
import { Card } from '../../theme/themeDefaults';
import { Kicker } from '../Typography';
import { hasContent, resolveContent } from '../../utils/vue';
import type { ContentCardOwnProps, ContentCardSlots } from './ContentCard.types';
import classes from './ContentCard.module.css';

defineOptions({ name: 'ContentCard', inheritAttrs: false });

// `undefined` explícito: os padrões vêm do useProps, para que theme.components.ContentCard.defaultProps funcione.
const rawProps = withDefaults(defineProps<ContentCardOwnProps>(), {
  kicker: undefined,
  title: undefined,
  image: undefined,
  imageAlt: undefined,
  imageHeight: undefined,
  actions: undefined,
  classNames: undefined,
  styles: undefined,
  vars: undefined,
  unstyled: undefined,
});
defineSlots<ContentCardSlots>();

const attrs = useAttrs();
const slots = useSlots();
const props = useProps('ContentCard', { imageHeight: 180 }, rawProps);

// Getters: o useStyles lê o input a cada chamada, então class/style/classNames continuam reativos.
const getStyles = useStyles({
  name: 'ContentCard',
  classes,
  props,
  get className() { return attrs.class; },
  get style() { return attrs.style as any; },
  get classNames() { return props.classNames as any; },
  get styles() { return props.styles as any; },
  get vars() { return props.vars as any; },
  get unstyled() { return props.unstyled; },
});

const kicker = () => resolveContent(props.kicker, slots.kicker);
const title = () => resolveContent(props.title, slots.title);
const actions = () => resolveContent(props.actions, slots.actions);
const body = () => resolveContent(undefined, slots.default);
/** URL (string) vira <img>; slot ou nó customizado é renderizado como está. */
const imageUrl = () => (!slots.image && typeof props.image === 'string' && props.image ? props.image : undefined);
const imageNode = () => resolveContent(props.image, slots.image);
</script>

<template>
  <Card v-bind="{ ...attrs, ...getStyles('root') }">
    <div v-if="imageUrl() || hasContent(imageNode())" v-bind="getStyles('image')">
      <img
        v-if="imageUrl()"
        :src="imageUrl()"
        :alt="props.imageAlt ?? ''"
        :style="{ height: `${props.imageHeight}px` }"
      />
      <component :is="imageNode" v-else />
    </div>
    <Kicker v-if="hasContent(kicker())" v-bind="getStyles('kicker')"><component :is="kicker" /></Kicker>
    <div v-if="hasContent(title())" v-bind="getStyles('title')"><component :is="title" /></div>
    <div v-if="hasContent(body())" v-bind="getStyles('body')"><component :is="body" /></div>
    <div v-if="hasContent(actions())" v-bind="getStyles('actions')"><component :is="actions" /></div>
  </Card>
</template>

// packages/ui/src/components/ContentCard/ContentCard.tsx
import {
  Card,
  factory,
  useProps,
  useStyles,
  type CardProps,
  type Factory,
  type StylesApiProps,
} from '@mantine/core';
import { Kicker } from '../Typography';
import classes from './ContentCard.module.css';

export type ContentCardStylesNames = 'root' | 'image' | 'kicker' | 'title' | 'body' | 'actions';

export interface ContentCardProps extends Omit<CardProps, 'classNames' | 'styles' | 'vars' | 'attributes' | 'title'>, StylesApiProps<ContentCardFactory> {
  /** Sobretítulo em caixa-alta */
  kicker?: React.ReactNode;
  title?: React.ReactNode;
  /** Imagem de capa (URL) ou nó customizado */
  image?: string | React.ReactNode;
  imageAlt?: string;
  imageHeight?: number;
  /** Botões/links no rodapé do card */
  actions?: React.ReactNode;
  children?: React.ReactNode;
}

export type ContentCardFactory = Factory<{
  props: ContentCardProps;
  ref: HTMLDivElement;
  stylesNames: ContentCardStylesNames;
}>;

/** Card de conteúdo: superfície branca sobre LightGray, borda suave e sombra pequena (ds-card). */
export const ContentCard = factory<ContentCardFactory>((_props) => {
  const props = useProps('ContentCard', { imageHeight: 180 }, _props);
  const {
    classNames, className, style, styles, unstyled, vars, attributes,
    kicker, title, image, imageAlt, imageHeight, actions, children, ...others
  } = props;

  const getStyles = useStyles<ContentCardFactory>({
    name: 'ContentCard',
    classes,
    props,
    className,
    style,
    classNames,
    styles,
    unstyled,
    attributes,
    vars,
  });

  return (
    <Card {...getStyles('root')} {...others}>
      {image && (
        <div {...getStyles('image')}>
          {typeof image === 'string' ? <img src={image} alt={imageAlt ?? ''} style={{ height: imageHeight }} /> : image}
        </div>
      )}
      {kicker && <Kicker {...getStyles('kicker')}>{kicker}</Kicker>}
      {title && <div {...getStyles('title')}>{title}</div>}
      {children && <div {...getStyles('body')}>{children}</div>}
      {actions && <div {...getStyles('actions')}>{actions}</div>}
    </Card>
  );
});

ContentCard.classes = classes;
ContentCard.displayName = '@jcdecor/ui/ContentCard';
