// packages/ui/src/components/ProductCard/ProductCard.tsx
import {
  ActionIcon,
  Button,
  Card,
  Group,
  Rating,
  Text,
  factory,
  useProps,
  useStyles,
  type CardProps,
  type Factory,
  type StylesApiProps,
} from '@mantine/core';
import { Fragment } from 'react';
import { IconHeart, IconHeartFilled, IconShoppingCart } from '@tabler/icons-react';
import { PriceTag, type PriceTagProps } from '../PriceTag';
import { Tag } from '../Tag';
import classes from './ProductCard.module.css';

export type ProductCardStylesNames = 'root' | 'media' | 'badges' | 'favorite' | 'category' | 'name' | 'price' | 'action';

export interface ProductCardProps
  extends Omit<CardProps, 'classNames' | 'styles' | 'vars' | 'attributes'>,
    StylesApiProps<ProductCardFactory> {
  name: string;
  image: string;
  href?: string;
  category?: string;
  price: number;
  oldPrice?: number;
  installments?: PriceTagProps['installments'];
  pixDiscount?: number;
  unit?: string;
  /** Selos extras (ex.: "Novo", "Frete grátis") */
  badges?: React.ReactNode[];
  /** Mostra selo "-X%" calculado a partir de oldPrice @default true */
  showDiscount?: boolean;
  rating?: number;
  reviews?: number;
  favorite?: boolean;
  onFavoriteChange?: (favorite: boolean) => void;
  actionLabel?: string;
  onAction?: () => void;
  /** Proporção da imagem (largura/altura) @default 1 */
  imageRatio?: number;
  /** Componente do link (ex.: Link do react-router) @default 'a' */
  linkComponent?: React.ElementType;
}

export type ProductCardFactory = Factory<{
  props: ProductCardProps;
  ref: HTMLDivElement;
  stylesNames: ProductCardStylesNames;
}>;

/** Card de produto do e-commerce: imagem, selos, nome, avaliação, preço e CTA. */
export const ProductCard = factory<ProductCardFactory>((_props) => {
  const props = useProps('ProductCard', { showDiscount: true, actionLabel: 'Comprar', imageRatio: 1, linkComponent: 'a' }, _props);
  const {
    classNames, className, style, styles, unstyled, vars, attributes,
    name, image, href, category, price, oldPrice, installments, pixDiscount, unit, badges, showDiscount,
    rating, reviews, favorite, onFavoriteChange, actionLabel, onAction, imageRatio, linkComponent: LinkComponent = 'a',
    ...others
  } = props;

  const getStyles = useStyles<ProductCardFactory>({
    name: 'ProductCard',
    classes,
    props,
    className,
    style,
    classNames,
    styles,
    unstyled,
    attributes,
    vars,
  });

  const discount = oldPrice && oldPrice > price ? Math.round((1 - price / oldPrice) * 100) : 0;
  const linkProps = href ? (LinkComponent === 'a' ? { href } : { to: href, href }) : {};
  const NameComponent: React.ElementType = href ? LinkComponent : 'div';

  return (
    <Card {...getStyles('root')} mod={{ interactive: Boolean(href || onAction) }} {...others}>
      <div {...getStyles('media')} style={{ ['--product-ratio' as string]: String(imageRatio) }}>
        <img src={image} alt={name} loading="lazy" />
        <div {...getStyles('badges')}>
          {showDiscount && discount > 0 && (
            <Tag tone="error" variant="filled">
              -{discount}%
            </Tag>
          )}
          {badges?.map((badge, index) => <Fragment key={index}>{badge}</Fragment>)}
        </div>
        {onFavoriteChange && (
          <ActionIcon
            {...getStyles('favorite')}
            variant="subtle"
            color={favorite ? 'danger' : 'obsidian'}
            radius="xl"
            aria-label={favorite ? 'Remover dos favoritos' : 'Adicionar aos favoritos'}
            aria-pressed={favorite}
            onClick={() => onFavoriteChange(!favorite)}
          >
            {favorite ? <IconHeartFilled size={18} /> : <IconHeart size={18} />}
          </ActionIcon>
        )}
      </div>
      {category && <div {...getStyles('category')}>{category}</div>}
      <NameComponent {...linkProps} {...getStyles('name')}>
        {name}
      </NameComponent>
      {rating !== undefined && (
        <Group gap={6} mb="xs">
          <Rating value={rating} fractions={2} readOnly size="xs" color="electric.4" />
          {reviews !== undefined && (
            <Text fz="xs" c="var(--ds-text-3)">
              ({reviews})
            </Text>
          )}
        </Group>
      )}
      <PriceTag
        {...getStyles('price')}
        value={price}
        oldValue={oldPrice}
        installments={installments}
        pixDiscount={pixDiscount}
        unit={unit}
      />
      {onAction && (
        <Button {...getStyles('action')} fullWidth leftSection={<IconShoppingCart size={18} />} onClick={onAction}>
          {actionLabel}
        </Button>
      )}
    </Card>
  );
});

ProductCard.classes = classes;
ProductCard.displayName = '@jcdecor/ui/ProductCard';

// packages/vue/src/components/ProductCard/ProductCard.vue
<script setup lang="ts">
import { useAttrs, useSlots } from 'vue';
import { ActionIcon, Button, Group, Rating, Text, resolveNode, useProps, useStyles } from '@mantine-vue/core';
import { Card } from '../../theme/themeDefaults';
import { IconHeart, IconHeartFilled, IconShoppingCart } from '@tabler/icons-vue';
import { PriceTag } from '../PriceTag';
import { Tag } from '../Tag';
import { useListenerCheck } from '../../utils/vue';
import type { ProductCardEmits, ProductCardOwnProps, ProductCardSlots } from './ProductCard.types';
import classes from './ProductCard.module.css';

defineOptions({ name: 'ProductCard', inheritAttrs: false });

// `undefined` explícito: os padrões vêm do useProps, e `favorite` ausente (≠ false) esconde o coração.
const rawProps = withDefaults(defineProps<ProductCardOwnProps>(), {
  href: undefined,
  category: undefined,
  oldPrice: undefined,
  installments: undefined,
  pixDiscount: undefined,
  unit: undefined,
  badges: undefined,
  showDiscount: undefined,
  rating: undefined,
  reviews: undefined,
  favorite: undefined,
  actionLabel: undefined,
  imageRatio: undefined,
  linkComponent: undefined,
  classNames: undefined,
  styles: undefined,
  vars: undefined,
  unstyled: undefined,
});
defineSlots<ProductCardSlots>();
const emit = defineEmits<ProductCardEmits>();

const attrs = useAttrs();
const slots = useSlots();
const hasListener = useListenerCheck();
const props = useProps(
  'ProductCard',
  { showDiscount: true, actionLabel: 'Comprar', imageRatio: 1, linkComponent: 'a' },
  rawProps,
);

const getStyles = useStyles({
  name: 'ProductCard',
  classes,
  props,
  get className() { return attrs.class; },
  get style() { return attrs.style as any; },
  get classNames() { return props.classNames as any; },
  get styles() { return props.styles as any; },
  get vars() { return props.vars as any; },
  get unstyled() { return props.unstyled; },
});

const discount = () =>
  props.oldPrice && props.oldPrice > props.price ? Math.round((1 - props.price / props.oldPrice) * 100) : 0;
/** Equivalente a `onFavoriteChange` passado no React: `v-model:favorite`, `:favorite` ou `@update:favorite`. */
const showFavorite = () => props.favorite !== undefined || hasListener('update:favorite');
/** Equivalente a `onAction` passado no React. */
const showAction = () => hasListener('action');
const linkProps = () => {
  const link = props.linkComponent ?? 'a';
  return props.href ? (link === 'a' ? { href: props.href } : { to: props.href, href: props.href }) : {};
};
const nameComponent = () => (props.href ? (props.linkComponent ?? 'a') : 'div');
const renderBadges = () => [...(props.badges ?? []).map((badge) => resolveNode(badge)), slots.badges?.()];
</script>

<template>
  <Card v-bind="{ ...attrs, ...getStyles('root') }" :mod="[{ interactive: Boolean(props.href || showAction()) }, (attrs as any).mod]">
    <div v-bind="getStyles('media', { style: { '--product-ratio': String(props.imageRatio) } })">
      <img :src="props.image" :alt="props.name" loading="lazy" />
      <div v-bind="getStyles('badges')">
        <Tag v-if="props.showDiscount && discount() > 0" tone="error" variant="filled">-{{ discount() }}%</Tag>
        <component :is="renderBadges" />
      </div>
      <ActionIcon
        v-if="showFavorite()"
        v-bind="getStyles('favorite')"
        variant="subtle"
        :color="props.favorite ? 'danger' : 'obsidian'"
        radius="xl"
        :aria-label="props.favorite ? 'Remover dos favoritos' : 'Adicionar aos favoritos'"
        :aria-pressed="Boolean(props.favorite)"
        @click="emit('update:favorite', !props.favorite)"
      >
        <IconHeartFilled v-if="props.favorite" :size="18" />
        <IconHeart v-else :size="18" />
      </ActionIcon>
    </div>
    <div v-if="props.category" v-bind="getStyles('category')">{{ props.category }}</div>
    <component :is="nameComponent()" v-bind="{ ...linkProps(), ...getStyles('name') }">{{ props.name }}</component>
    <Group v-if="props.rating !== undefined" :gap="6" mb="xs">
      <Rating :model-value="props.rating" :fractions="2" read-only size="xs" color="electric.4" />
      <Text v-if="props.reviews !== undefined" fz="xs" c="var(--ds-text-3)">({{ props.reviews }})</Text>
    </Group>
    <PriceTag
      v-bind="getStyles('price')"
      :value="props.price"
      :old-value="props.oldPrice"
      :installments="props.installments"
      :pix-discount="props.pixDiscount"
      :unit="props.unit"
    />
    <Button v-if="showAction()" v-bind="getStyles('action')" full-width @click="emit('action', $event)">
      <template #leftSection><IconShoppingCart :size="18" /></template>
      {{ props.actionLabel }}
    </Button>
  </Card>
</template>
