// apps/docs/src/demos/floating-indicator/underline.demo.tsx
import { useState } from 'react';
import { Box, FloatingIndicator, Group, UnstyledButton, Text } from '@jcdecor/ui';
import type { DemoMeta } from '../../kit/demos';

export const meta: DemoMeta = { centered: true };

const items = ['Descrição', 'Medidas', 'Instalação', 'Avaliações'];

export default function Demo() {
  const [root, setRoot] = useState<HTMLDivElement | null>(null);
  const [refs, setRefs] = useState<Record<string, HTMLButtonElement | null>>({});
  const [active, setActive] = useState(items[0]);

  const setRef = (item: string) => (node: HTMLButtonElement | null) => {
    refs[item] = node;
    setRefs(refs);
  };

  return (
    <Box ref={setRoot} pos="relative" style={{ borderBottom: '1px solid var(--ds-border-soft)' }}>
      <Group gap="lg">
        {items.map((item) => (
          <UnstyledButton key={item} ref={setRef(item)} onClick={() => setActive(item)} py="sm" style={{ position: 'relative', zIndex: 1 }}>
            <Text fz="sm" fw={600} c={active === item ? 'var(--ds-text)' : 'var(--ds-text-3)'}>
              {item}
            </Text>
          </UnstyledButton>
        ))}
      </Group>

      {/* O indicador acompanha o alvo; aqui ele vira uma linha de 2px na base. */}
      <FloatingIndicator
        target={refs[active]}
        parent={root}
        transitionDuration={200}
        style={{ borderBottom: '2px solid var(--ds-primary)' }}
      />
    </Box>
  );
}

// apps/docs/src/demos/floating-indicator/underline.demo.vue
<script lang="ts">
export const meta = { centered: true };
</script>

<script setup lang="ts">
import { reactive, ref } from 'vue';
import { Box, FloatingIndicator, Group, Text, UnstyledButton } from '@jcdecor/vue';

const items = ['Descrição', 'Medidas', 'Instalação', 'Avaliações'];

const root = ref<HTMLElement | null>(null);
const refs = reactive<Record<string, HTMLElement | null>>({});
const active = ref(items[0]);

const setRoot = (el: Element | null) => (root.value = el as HTMLElement | null);
const setRef = (item: string) => (el: Element | null) => (refs[item] = el as HTMLElement | null);
</script>

<template>
  <Box :root-ref="setRoot" pos="relative" :style="{ borderBottom: '1px solid var(--ds-border-soft)' }">
    <Group gap="lg">
      <UnstyledButton
        v-for="item in items"
        :key="item"
        :root-ref="setRef(item)"
        py="sm"
        :style="{ position: 'relative', zIndex: 1 }"
        @click="active = item"
      >
        <Text fz="sm" :fw="600" :c="active === item ? 'var(--ds-text)' : 'var(--ds-text-3)'">{{ item }}</Text>
      </UnstyledButton>
    </Group>

    <!-- O indicador acompanha o alvo; aqui ele vira uma linha de 2px na base. -->
    <FloatingIndicator
      :target="refs[active]"
      :parent="root"
      :transition-duration="200"
      :style="{ borderBottom: '2px solid var(--ds-primary)' }"
    />
  </Box>
</template>
