// apps/docs/src/demos/combobox/header-footer.demo.tsx
import { useState } from 'react';
import { Anchor, Combobox, TextInput, useCombobox } from '@jcdecor/ui';
import { IconSearch } from '@tabler/icons-react';
import type { DemoMeta } from '../../kit/demos';

export const meta: DemoMeta = { centered: true, maxWidth: 420 };

const recentes = ['Piso vinílico carvalho', 'Papel de parede listrado', 'Cortina blackout cinza'];
const populares = ['Painel ripado', 'Grama sintética', 'Tatame infantil'];

export default function Demo() {
  const combobox = useCombobox();
  const [value, setValue] = useState('');

  return (
    <Combobox
      store={combobox}
      onOptionSubmit={(val) => {
        setValue(val);
        combobox.closeDropdown();
      }}
    >
      <Combobox.Target>
        <TextInput
          label="Buscar produtos"
          placeholder="Ex.: piso para cozinha"
          leftSection={<IconSearch size={18} />}
          value={value}
          onChange={(event) => setValue(event.currentTarget.value)}
          onClick={() => combobox.openDropdown()}
          onFocus={() => combobox.openDropdown()}
          onBlur={() => combobox.closeDropdown()}
        />
      </Combobox.Target>

      <Combobox.Dropdown>
        <Combobox.Header>Sugestões para você</Combobox.Header>
        <Combobox.Options>
          <Combobox.Group label="Buscas recentes">
            {recentes.map((item) => (
              <Combobox.Option value={item} key={item}>
                {item}
              </Combobox.Option>
            ))}
          </Combobox.Group>
          <Combobox.Group label="Mais buscados">
            {populares.map((item) => (
              <Combobox.Option value={item} key={item}>
                {item}
              </Combobox.Option>
            ))}
          </Combobox.Group>
        </Combobox.Options>
        <Combobox.Footer>
          <Anchor fz="sm" href="#" onClick={(event) => event.preventDefault()}>
            Ver todas as categorias
          </Anchor>
        </Combobox.Footer>
      </Combobox.Dropdown>
    </Combobox>
  );
}

// apps/docs/src/demos/combobox/header-footer.demo.vue
<script lang="ts">
export const meta = { centered: true, maxWidth: 420 };
</script>

<script setup lang="ts">
import { ref } from 'vue';
import { Anchor, Combobox, ComboboxDropdown, ComboboxFooter, ComboboxGroup, ComboboxHeader, ComboboxOption, ComboboxOptions, ComboboxTarget, TextInput, useCombobox } from '@jcdecor/vue';
import { IconSearch } from '@tabler/icons-vue';

const recentes = ['Piso vinílico carvalho', 'Papel de parede listrado', 'Cortina blackout cinza'];
const populares = ['Painel ripado', 'Grama sintética', 'Tatame infantil'];

const combobox = useCombobox();
const value = ref('');

const handleSubmit = (val: string) => {
  value.value = val;
  combobox.closeDropdown();
};
</script>

<template>
  <Combobox :store="combobox" @option-submit="handleSubmit">
    <ComboboxTarget>
      <TextInput
        v-model="value"
        label="Buscar produtos"
        placeholder="Ex.: piso para cozinha"
        @click="combobox.openDropdown()"
        @focus="combobox.openDropdown()"
        @blur="combobox.closeDropdown()"
      >
        <template #leftSection><IconSearch :size="18" /></template>
      </TextInput>
    </ComboboxTarget>

    <ComboboxDropdown>
      <ComboboxHeader>Sugestões para você</ComboboxHeader>
      <ComboboxOptions>
        <ComboboxGroup label="Buscas recentes">
          <ComboboxOption v-for="item in recentes" :key="item" :value="item">{{ item }}</ComboboxOption>
        </ComboboxGroup>
        <ComboboxGroup label="Mais buscados">
          <ComboboxOption v-for="item in populares" :key="item" :value="item">{{ item }}</ComboboxOption>
        </ComboboxGroup>
      </ComboboxOptions>
      <ComboboxFooter>
        <Anchor fz="sm" href="#" @click.prevent>Ver todas as categorias</Anchor>
      </ComboboxFooter>
    </ComboboxDropdown>
  </Combobox>
</template>
